name: ORT Analysis for JavaScript Project

on:
  pull_request:
    paths:
      - 'package.json'  # Only trigger on changes to package.json

jobs:
  ort-analysis:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Debug GitHub Token Permissions
        run: |
          echo "GitHub Token permissions:"
          echo "${{ toJSON(github.token_permissions) }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for diff check

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: ORT Analysis
        id: ort_analysis
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
<<<<<<< Updated upstream
          args: analyze -i .. -f JSON --use-locks --allow-dynamic-versions
=======
          args: analyze -i .. -f JSON --use-locks
>>>>>>> Stashed changes

      - name: Process ORT Results
        run: |
          cat ${{ steps.ort_analysis.outputs.analyzer-result-json }} | jq -r '.packages[] | "\(.id.name):\(.id.version)"' | sed 's/ /_/g' > packages.txt
          echo "::set-output name=packages::$(cat packages.txt | tr '\n' ' ')"
        id: process_ort_results

      # - name: ORT Analysis
      #   id: ort_analysis
      #   run: |
      #     echo "::set-output name=packages::$(ort analyze -i ../.. -f JSON --use-locks --allow-dynamic-versions | jq -r '.packages[] | "\(.id.name):\(.id.version)"' | sed 's/ /_/g')"
      #     # echo "::set-output name=packages::$(ort analyze -i .. -f JSON --use-locks --allow-dynamic-versions)"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Assuming ORT needs this for some operations

      - name: Check for New Dependencies
        id: check_new_deps
        run: |
          git fetch origin $GITHUB_BASE_REF
          if git diff --name-only origin/$GITHUB_BASE_REF..HEAD -- package.json | grep 'package.json'; then
            echo "::set-output name=new_deps::true"
          else
            echo "::set-output name=new_deps::false"
          fi

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const packages = `${{ steps.ort_analysis.outputs.packages }}`.split('\n').map(p => p.replace(/_/g, ' '));
            const newDeps = `${{ steps.check_new_deps.outputs.new_deps }}` === 'true';
            const rawPackages = `JSON.stringify(${{ steps.ort_analysis.outputs.packages }})`;
            const outputPackages = `${{ steps.ort_analysis.outputs.packages }}`;

            let commentBody = `### ORT Scan Results\n`;
            commentBody += `\n**New dependencies added:** ${newDeps ? 'Yes' : 'No'}`;
            commentBody += `\n#### Dependencies:\n${packages.map(p => `- ${p}`).join('\n')}\n`;
            commentBody += `\n#### Raw packages:\n${rawPackages}\n`;
            commentBody += `\n#### Output packages:\n${outputPackages}\n`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });