name: ORT Analysis for JavaScript Project

on:
  pull_request:
    paths:
      - 'package.json'  # Only trigger on changes to package.json

jobs:
  ort-analysis:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Debug GitHub Token Permissions
        run: |
          echo "GitHub Token permissions:"
          echo "${{ toJSON(github.token_permissions) }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for diff check

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      # - name: ORT Analysis
      #   id: ort_analysis
      #   uses: oss-review-toolkit/ort-ci-github-action@v1
      #   with:
      #     args: analyze -i .. -f JSON --use-locks --allow-dynamic-versions

      - name: Run ORT Analysis and Capture Output
        id: ort_analysis
        run: |
          # We use docker to run ORT, capturing stdout
          # ORT_RESULT=$(docker run --rm -v $(pwd) ghcr.io/oss-review-toolkit/ort analyze -i .. -f JSON --use-locks --allow-dynamic-versions)


          docker pull ghcr.io/oss-review-toolkit/ort:latest  # Pull the latest image
          ORT_RESULT=$(docker run --rm -v $(pwd):$(pwd) ghcr.io/oss-review-toolkit/ort:latest analyze -i .. -f JSON --use-locks --allow-dynamic-versions)
          echo "Captured ORT output:"


          echo "======= output"
          echo "$ORT_RESULT"
          # Save ORT result to an environment variable for use in subsequent steps
          echo "ORT_RESULT=$ORT_RESULT" >> $GITHUB_ENV
          echo "::set-output name=packages::$(echo "${{ env.ORT_RESULT }}" | jq -r '.packages[] | "\(.id.name):\(.id.version)"' | sed 's/ /_/g' | tr '\n' ' ')"

      - name: Check for New Dependencies
        id: check_new_deps
        run: |
          git fetch origin $GITHUB_BASE_REF
          if git diff --name-only origin/$GITHUB_BASE_REF..HEAD -- package.json | grep 'package.json'; then
            echo "::set-output name=new_deps::true"
          else
            echo "::set-output name=new_deps::false"
          fi

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ortResult = `${{ env.ORT_RESULT }}`.split('\n').map(p => p.replace(/_/g, ' '));
            const packages = `${{ steps.ort_analysis.outputs.packages }}`.split('\n').map(p => p.replace(/_/g, ' '));
            const newDeps = `${{ steps.check_new_deps.outputs.new_deps }}` === 'true';
            const rawPackages = `JSON.stringify(${{ steps.ort_analysis.outputs.packages }})`;
            const outputPackages = `${{ steps.ort_analysis.outputs.packages }}`;

            let commentBody = `### ORT Scan Results\n`;
            commentBody += `\n**New dependencies added:** ${newDeps ? 'Yes' : 'No'}`;
            commentBody += `\n#### Dependencies:\n${packages.map(p => `- ${p}`).join('\n')}\n`;
            commentBody += `\n#### Raw packages:\n${rawPackages}\n`;
            commentBody += `\n#### Output packages:\n${outputPackages}\n`;
            commentBody += `\n#### Ort result:\n${ortResult}\n`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });