name: ORT Analysis for JavaScript Project

on:
  pull_request:
    paths:
      # todo: skip node_modules
      - '**/**/package.json' # Trigger when package.json changes

jobs:
  ort-analysis:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Debug GitHub Token Permissions
        run: |
          echo "GitHub Token permissions:"
          echo "${{ toJSON(github.token_permissions) }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for diff check

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # - name: Install npm dependencies
      #   run: npm install

      - name: Create Output Directory
        run: mkdir -p ort-output

      - name: Set Permissions for $PWD and ort-output
        run: |
          sudo chown -R $(whoami) "$PWD"  # Ensure $PWD has read/write permissions
          sudo chmod -R 777 "$PWD"        # Make $PWD writable

          mkdir -p ort-output              # Ensure ort-output directory exists
          sudo chown -R $(whoami) "$PWD/ort-output"  # Set permissions for ort-output
          sudo chmod -R 777 "$PWD/ort-output"        # Make ort-output writable

      - name: Run ORT analyze and extract dependencies
        id: ort-analyze
        run: |
          echo "Running ORT analyze..."
          # json_output=$(docker run ghcr.io/oss-review-toolkit/ort:latest -v $PWD/:/$PWD analyze -i . -o . --output-formats JSON)
          # json_output=$(docker run ghcr.io/oss-review-toolkit/ort:latest -v $PWD/:/$PWD analyze -i . -o . --output-formats JSON)
          # json_output=$(docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/oss-review-toolkit/ort:latest analyze -i . -o /workspace --output-formats JSON)
          # json_output=$(docker run --rm -v "$PWD:/workspace" -v "$PWD/ort-output:/ort-output" -w /workspace ghcr.io/oss-review-toolkit/ort:latest analyze -i . -o /ort-output --output-formats JSON)

          json_output=$(docker run --rm -v "$PWD:$PWD" -w "$PWD" ghcr.io/oss-review-toolkit/ort:latest analyze -i $PWD -o $PWD/ort-output --output-formats JSON)

          echo "==== pwd:"
          ls -l

          # ls -l ./workspace
          echo "==== ort output:"
          ls -l ort-output
          ls -l ./ort-output

          echo "==== ort output:"
          json_output=$(cat ./ort-output/analyzer-result.json)

          echo "======== json output"
          # echo "$json_output"

          # dependencies=$(echo "$json_output" | jq -r '.analyzer.result.projects[].scopes[].dependencies[].id' | tr '\n' ',')
          # dependencies=$(cat ort-output/analyzer/result.json | jq -r '.analyzer.result.projects[].scopes[].dependencies[] | select(.vulnerabilities != null) | .id')
          # dependencies=$(echo "$json_output")
          # dependencies=$(echo "$json_output" | jq -r '.analyzer.result.projects[].scopes[].dependencies[].id' | tr '\n' ',')

          dependencies=$(echo "$json_output" | jq -r '.analyzer.result.packages[] | select(.vulnerabilities != null and (.vulnerabilities | length > 0)) | .id'
          echo "$dependencies"

          echo "$dependencies"
          echo "packages=${dependencies}" >> $GITHUB_ENV
          echo "Detected packages: $dependencies"

      # - name: Run ORT analyze
      #   id: ort-analyze
      #   uses: oss-review-toolkit/ort-ci-github-action@v1
      #   with:
      #     command: "analyze"
      #     args: "--package-managers NPM --output-formats JSON --output-dir ort-results"
      #     input-path: ".."

      # - name: Extract and set dependencies
      #   id: extract-dependencies
      #   run: |
      #     ORT_JSON_PATH=$(find ort-results ort -name "analyzer-result.json" 2>/dev/null | head -n 1)
      #     if [[ -z "$ORT_JSON_PATH" ]]; then
      #       echo "Error: analyzer-result.json not found!"
      #       exit 1
      #     fi
      #     echo "Found ORT JSON file at $ORT_JSON_PATH"
      #     dependencies=$(jq -r '.analyzer.result.projects[].scopes[].dependencies[].id' "$ORT_JSON_PATH" | tr '\n' ',')
      #     echo "packages=${dependencies}" >> $GITHUB_ENV

      - name: Check for New Dependencies
        id: check_new_deps
        run: |
          git fetch origin $GITHUB_BASE_REF
          if git diff --name-only origin/$GITHUB_BASE_REF..HEAD -- package.json | grep 'package.json'; then
            echo "::set-output name=new_deps::true"
          else
            echo "::set-output name=new_deps::false"
          fi

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ortResult = `${{ env.ORT_RESULT }}`.split('\n').map(p => p.replace(/_/g, ' '));
            const packages = `${{ steps.ort_analysis.outputs.packages }}`.split('\n').map(p => p.replace(/_/g, ' '));
            const newDeps = `${{ steps.check_new_deps.outputs.new_deps }}` === 'true';
            const rawPackages = `JSON.stringify(${{ steps.ort_analysis.outputs.packages }})`;
            const outputPackages = `${{ steps.ort_analysis.outputs.packages }}`;

            let commentBody = `### ORT Scan Results\n`;
            commentBody += `\n**New dependencies added:** ${newDeps ? 'Yes' : 'No'}`;
            commentBody += `\n#### Dependencies:\n${packages.map(p => `- ${p}`).join('\n')}\n`;
            commentBody += `\n#### Raw packages:\n${rawPackages}\n`;
            commentBody += `\n#### Output packages:\n${outputPackages}\n`;
            commentBody += `\n#### Ort result:\n${ortResult}\n`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });